services:
  hotdog-app:
    image: ghcr.io/MarkoPoloResearchLab/hotdog:latest
    container_name: hotdog-app
    restart: unless-stopped
    gpus: all
    ports:
      - "5000:5000"
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility,video
